language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip3 install termcolor
  - pip3 install coveralls
# command to run tests
script:
  - coverage run test_rpn.py
after_success:
  - coveralls